#!/bin/bash


dir=$1
text=$2
a=1

for char in `cat $text`
do
#	echo $dir/$pic
#	echo "a = " $a
	mv $dir/photo$a $dir/$char
	a=$((a+1))
done

#file nay` dung chay cai name.txt de doi ten thu muc vau moi' segment ben QT thanh` thu muc alphabet